### ISSUE TITLE
Multyplayer buged since beta 20 worked till beta19

### ISSUE THREAD

**Issue by Deromer** [Azanor/thaumcraft-beta#1410]
since beta 20 all automatic alchemy and everthing that drains esencias from flasks dont work anymore i hope this bug get's fixed soon 
i really enjoy playing this mod with my frinds but being stuck on version 19 is a bit of a bummer :/

**Comment by Amelia-** [comment]
I am not experiencing this issue on multiplayer with beta 24. Perhaps another mod is causing this?

**Comment by F9Alejandro** [comment]
@Deromer What mods do you have running with TC Beta 24?

**Comment by Minamikaze392** [comment]
@Deromer there was a bug in Beta 20 that the effect of essentia transferring in the air was not rendered properly. Only a graphic bug though and it got fixed in later versions. You'd better see if you can reproduce the bug in the latest version before reporting :)

**Comment by Azanor** [comment]
Any update on this?

**Comment by Deromer** [comment]
i reset my server and its still not working everthing that pulls from flasks does not seem to work

**Comment by F9Alejandro** [comment]
@Azanor is the rendering effect of essentia transferring in the air using minecraft particle class? or linked to that setting?

**Comment by Minamikaze392** [comment]
@Deromer actually which version of Thaumcraft 6 is your server in?

**Comment by Deromer** [comment]
I tried version 20 23 and 24 all have the same issue
