### ISSUE TITLE
Unable to craft crucible

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#278]
Salis Mundus doesn't create a crucible when right clicked on a cauldron in Beta5

**Comment by mujmajnkraft** [comment]
Actually, game crashes with the following report:
https://paste.ubuntu.com/p/3gXKjgQC8G/

**Comment by Patataking** [comment]
Without any other mods installed using BETA5 it crashes for me. I have tried both the newest and the recommended Forge versions.

Report:
https://paste.ubuntu.com/p/PHNwdGhrbb/

**Comment by twothe** [comment]
#275

**Comment by murven** [comment]
I am experiencing this issue in 6.1.BETA26 as part of Enigmatica 2 Expert. No crash, just nothing happens. Is this a known issue?

**Comment by twothe** [comment]
It has been fixed a year ago, so I doubt this is a known issue.

**Comment by murven** [comment]
Yes, this is fixed. This is just my ignorance of the mod. For the benefit of anyone else who may find this issue looking for the same, you cannot create a crucible by just randomly applying salis mundus to a cauldron because you read it on a wiki page. You have to actually go through the Thaumonomicon and do the appropriate research before you are able to. If anything, maybe it would be a nice to have feature to display some text on screen like "The cauldron reacts, but I still do not have enough knowledge to control the reaction, I should research some more..." when you click it before you can actually create it. But definitely not a bug.

**Comment by twothe** [comment]
Or a "RTFM" achievement like Immersive Engineering when you actually read the Thaumonomicon. ;)

I mean he made such a great tutorial book and people still do not read it, it's a shame...
