### ISSUE TITLE
Recipes in Crucible Not Working

### ISSUE THREAD

**Issue by Boolyman** [Azanor/thaumcraft-beta#550]
Thaumcraft 6 1.12.2
Forge 14.23.2.2654

I drop in enough Vis to fulfill the recipes, and when its time to drop the catalyst in, the crucible just eats it up and adds the Vis to the total.  I have tried both Nitor and Alchemical Brass.  Here is video of me trying the Nitor.  In the video I try adding the catalyst by dropping the glowstone in first... then again by right clicking it in.  Both just simply eat the glowstone and add it to the Vis totals.

https://youtu.be/OeWtkLMIVFo

**Comment by Kyozan** [comment]
What version of the beta are you using? This was a problem in beta 10, but should be fixed in version 11.

**Comment by EnderofGames** [comment]
I am also having this issue, 1.12.2; I updated to beta 11 and created a new world. Still could not perform alchemy. I tried three recipes, Yellow Nitor and a gold cluster were two of them.

**Comment by FrankieRozsa1** [comment]
hey im still having this issue? what do you mean about update arrow? i dont know how to do it
