### ISSUE TITLE
[B14] Server crash upon restart after updating B13 to B14

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#836]
I have no idea whether there is some setting I can change to tell the server to just re-initialize this "TickNextTick list" and continue.  It looks as though it has basically finished loading everything and is ready to accept connections at the moment that it crashes.  This appears to be highly repeatable; I've just watched it crash the exact same way three times in a row.  If I roll back to beta 13, **changing nothing else**, the server starts fine (though I have to tell Forge it's OK to delete the new blocks registered by B14).

...
[17:55:59] [Server thread/INFO] [immersiveengineering]: WorldData loading
[17:55:59] [Server thread/INFO] [immersiveengineering]: WorldData retrieved
[17:55:59] [Thread-18/INFO] [THAUMCRAFT]: Starting aura thread for dim 7
[17:56:00] [Thread-19/INFO] [THAUMCRAFT]: Starting aura thread for dim 1
[17:56:00] [Thread-20/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
[17:56:00] [Thread-21/INFO] [THAUMCRAFT]: Starting aura thread for dim 66
[17:56:00] [Thread-22/INFO] [THAUMCRAFT]: Starting aura thread for dim 0
[17:56:01] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 7
[17:56:01] [Server thread/INFO] [FML]: Unloading dimension 7
[17:56:01] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 1
[17:56:01] [Server thread/INFO] [FML]: Unloading dimension 1
[17:56:01] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1
[17:56:01] [Server thread/INFO] [FML]: Unloading dimension -1
[17:56:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LibLoader (# LibLoader.jar)
  CoreMod (TickProfiler-1.12-0.0.4.jar)
  VanillaFixLoadingPlugin (VanillaFix-1.0.4-35.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 5/22/18 5:50 PM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:691)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:691)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
        Level name: CaerDhu
        All players: 0 total; []
        Chunk stats: ServerChunkCache: 720 Drop: 0
        Level seed: -6634953474348370960
        Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
        Level generator options:
        Level spawn location: World: (150,64,330), Chunk: (at 6,4,10 in 9,20; contains blocks 144,0,320 to 159,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 18879544 game time, 18890078 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 9097 (now: false), thunder time: 77927 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 4.15.15-gentoo-narn
        Java Version: 1.8.0_172, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 788527064 bytes (751 MB) / 2147483648 bytes (2048 MB) up to 6442450944 bytes (6144 MB)
        JVM Flags: 10 total; -Xmx6G -Xms2G -Xss16M -XX:+UseG1GC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
        IntCache: cache: 1, tcache: 1, allocated: 3, tallocated: 104
        FML: MCP 9.42 Powered by Forge 14.23.3.2677 92 mods loaded, 92 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State     | ID                         | Version                  | Source                                          | Signature                                |
        |:--------- |:-------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
        | UCHIJAAAA | minecraft                  | 1.12.2                   | minecraft.jar                                   | None                                     |
        | UCHIJAAAA | mcp                        | 9.42                     | minecraft.jar                                   | None                                     |
        | UCHIJAAAA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.3.2677-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAAA | forge                      | 14.23.3.2677             | forge-1.12.2-14.23.3.2677-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAAA | bspkrscore                 | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar          | None                                     |
        | UCHIJAAAA | treecapitator              | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar           | None                                     |
        | UCHIJAAAA | architecturecraft          | @VERSION@                | architecturecraft-1.12-2.68.jar                 | None                                     |
        | UCHIJAAAA | basemetals                 | 2.5.0-beta5              | BaseMetals-1.12-2.5.0-beta5.214.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | baubles                    | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
        | UCHIJAAAA | bibliocraft                | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
        | UCHIJAAAA | biometweaker               | 3.2.345                  | BiomeTweaker-1.12.2-3.2.345.jar                 | bdea6e9d19f35da4858ffcc93210c6207dd590bd |
        | UCHIJAAAA | biomesoplenty              | 7.0.1.2382               | BiomesOPlenty-1.12.2-7.0.1.2382-universal.jar   | None                                     |
        | UCHIJAAAA | redstoneflux               | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
        | UCHIJAAAA | cofhcore                   | 4.4.1                    | CoFHCore-1.12.2-4.4.1.12-universal.jar          | None                                     |
        | UCHIJAAAA | boptools                   | 0.0.3                    | boptools-1.12-0.0.3.0.jar                       | None                                     |
        | UCHIJAAAA | carryon                    | 1.8                      | CarryOn+MC1.12.2+v1.8.jar                       | None                                     |
        | UCHIJAAAA | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
        | UCHIJAAAA | codechickenlib             | 3.1.8.341                | CodeChickenLib-1.12.2-3.1.8.341-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | chickenchunks              | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | chunkpregenerator          | 1.7                      | Chunk+Pregenerator+V1.12-1.7.1.jar              | None                                     |
        | UCHIJAAAA | classiccombat              | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                    | None                                     |
        | UCHIJAAAA | clayworldgen               | 1.1.0-1.12               | ClayWorldGen-1.1.0-1.12.0.jar                   | None                                     |
        | UCHIJAAAA | cofhworld                  | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
        | UCHIJAAAA | crafttweaker               | 4.1.6                    | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
        | UCHIJAAAA | jei                        | 4.9.1.169                | jei_1.12.2-4.9.1.169.jar                        | None                                     |
        | UCHIJAAAA | crafttweakerjei            | 2.0.0                    | CraftTweaker2-1.12-4.1.6.jar                    | None                                     |
        | UCHIJAAAA | dirt2path                  | 1.7.0                    | dirt2path-1.7.0.jar                             | None                                     |
        | UCHIJAAAA | endercore                  | 1.12.2-0.5.20            | EnderCore-1.12.2-0.5.20.jar                     | None                                     |
        | UCHIJAAAA | thermalfoundation          | 2.4.1                    | ThermalFoundation-1.12.2-2.4.1.15-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | UCHIJAAAA | thermalexpansion           | 5.4.2                    | ThermalExpansion-1.12.2-5.4.2.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | UCHIJAAAA | enderio                    | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderiointegrationtic      | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderiobase                | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderioconduits            | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderiointegrationforestry | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderiointegrationticlate  | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderiomachines            | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderiopowertools          | 5.0.22                   | EnderIO-1.12.2-5.0.22.jar                       | None                                     |
        | UCHIJAAAA | enderstorage               | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | erebus                     | 1.0.22                   | Erebus-1.0.22.jar                               | None                                     |
        | UCHIJAAAA | minegems                   | 1.2.3                    | ExtraGems+1.12.2++(v.1.2.3).jar                 | None                                     |
        | UCHIJAAAA | fenceoverhaul              | 1.3.4                    | FenceOverhaul-1.3.4.jar                         | None                                     |
        | UCHIJAAAA | forgemultipartcbe          | 2.4.2.58                 | ForgeMultipart-1.12.2-2.4.2.58-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | microblockcbe              | 2.4.2.58                 | ForgeMultipart-1.12.2-2.4.2.58-universal.jar    | None                                     |
        | UCHIJAAAA | minecraftmultipartcbe      | 2.4.2.58                 | ForgeMultipart-1.12.2-2.4.2.58-universal.jar    | None                                     |
        | UCHIJAAAA | waila                      | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                       | None                                     |
        | UCHIJAAAA | immersiveengineering       | 0.12-81                  | ImmersiveEngineering-0.12-81.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
        | UCHIJAAAA | immersivetech              | 1.3.7                    | immersivetech-1.12-1.3.7.jar                    | None                                     |
        | UCHIJAAAA | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
        | UCHIJAAAA | ironchest                  | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
        | UCHIJAAAA | journeymap                 | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
        | UCHIJAAAA | kleeslabs                  | 5.4.8                    | KleeSlabs_1.12.2-5.4.8.jar                      | None                                     |
        | UCHIJAAAA | levels                     | 2.0.3                    | levels-2.0.3.jar                                | None                                     |
        | UCHIJAAAA | login_shield               | 1.12.2-1-g24c2a5e        | Login_Shield-1.12.2-1-g24c2a5e.jar              | None                                     |
        | UCHIJAAAA | malisiscore                | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
        | UCHIJAAAA | malisisblocks              | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                  | None                                     |
        | UCHIJAAAA | malisisdoors               | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
        | UCHIJAAAA | mekanism                   | 1.12.2-9.4.5.340         | Mekanism-1.12.2-9.4.5.340.jar                   | None                                     |
        | UCHIJAAAA | mekanismgenerators         | 9.4.4                    | MekanismGenerators-1.12.2-9.4.5.340.jar         | None                                     |
        | UCHIJAAAA | mekanismtools              | 9.4.4                    | MekanismTools-1.12.2-9.4.5.340.jar              | None                                     |
        | UCHIJAAAA | mineralogy                 | 3.4.0                    | Mineralogy-1.12-3.4.0.22.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | mobcontroller              | 1.1                      | MobController-1.12.2-1.1.jar                    | None                                     |
        | UCHIJAAAA | morpheus                   | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                         | None                                     |
        | UCHIJAAAA | mrtjpcore                  | 2.1.1.28                 | MrTJPCore-1.12.2-2.1.1.28-universal.jar         | None                                     |
        | UCHIJAAAA | mycommands                 | 1.12.2-01                | MyCommands-1.12.2-01.jar                        | None                                     |
        | UCHIJAAAA | naturescompass             | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
        | UCHIJAAAA | nethermetals               | 1.2.0-beta3              | NetherMetals-1.12-1.2.0-beta3.52.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | netherportalfix            | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar               | None                                     |
        | UCHIJAAAA | nmsot                      | 1.2.1-mc1.12             | NoMobSpawningOnTrees-1.2.1-mc1.12.jar           | None                                     |
        | UCHIJAAAA | nei                        | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | orespawn                   | 3.3.0                    | OreSpawn-1.12-3.3.0.136.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | projectred-core            | 4.8.6.76                 | ProjectRed-1.12.2-4.8.6.76-Base.jar             | None                                     |
        | UCHIJAAAA | projectred-integration     | 4.8.6.76                 | ProjectRed-1.12.2-4.8.6.76-integration.jar      | None                                     |
        | UCHIJAAAA | projectred-transmission    | 4.8.6.76                 | ProjectRed-1.12.2-4.8.6.76-integration.jar      | None                                     |
        | UCHIJAAAA | projectred-illumination    | 4.8.6.76                 | ProjectRed-1.12.2-4.8.6.76-lighting.jar         | None                                     |
        | UCHIJAAAA | projectred-exploration     | 4.8.6.76                 | ProjectRed-1.12.2-4.8.6.76-world.jar            | None                                     |
        | UCHIJAAAA | redstonearsenal            | 2.4.2                    | RedstoneArsenal-1.12.2-2.4.2.9-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | UCHIJAAAA | sgcraft                    | 1.13.2                   | SGCraft-1.0-mc1.12.2.jar                        | None                                     |
        | UCHIJAAAA | flammpfeil.slashblade      | mc1.12-r12               | SlashBlade-mc1.12-r12.jar                       | None                                     |
        | UCHIJAAAA | sophisticatedwolves        | 3.13.2                   | SophisticatedWolves-1.12.2-3.13.2.jar           | None                                     |
        | UCHIJAAAA | storagedrawers             | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
        | UCHIJAAAA | thaumcraft                 | 6.1.BETA14               | Thaumcraft-1.12.2-6.1.BETA14.jar                | None                                     |
        | UCHIJAAAA | thaumicjei                 | 1.2.1                    | ThaumicJEI-1.12.2-1.2.1-4.jar                   | None                                     |
        | UCHIJAAAA | thermaldynamics            | 2.4.1                    | ThermalDynamics-1.12.2-2.4.1.10-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | UCHIJAAAA | tickprofiler               | 1.12-0.0.4               | TickProfiler-1.12-0.0.4.jar                     | None                                     |
        | UCHIJAAAA | torchmaster                | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
        | UCHIJAAAA | translocators              | 2.5.0.70                 | Translocators-1.12.2-2.5.0.70-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | twilightforest             | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
        | UCHIJAAAA | underphangables            | 1.0.0                    | underphangables-1.12.0-1.0.0.jar                | None                                     |
        | UCHIJAAAA | vanillafix                 | 1.0.4+35                 | VanillaFix-1.0.4-35.jar                         | None                                     |
        | UCHIJAAAA | wawla                      | 2.5.253                  | Wawla-1.12.2-2.5.253.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | worldedit                  | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |

        Loaded coremods (and transformers):
IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)

EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LibLoader (# LibLoader.jar)

CoreMod (TickProfiler-1.12-0.0.4.jar)

VanillaFixLoadingPlugin (VanillaFix-1.0.4-35.jar)

        Ender IO: No known problems detected.

        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        !!!You are looking at the diagnostics information, not at the crash.       !!!
        !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        Suspected Mods: Unknown
        Profiler Position: N/A (disabled)
        Player Count: 0 / 20; []
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by captcookie** [comment]
I am also having this same exact issue.

**Comment by nop277** [comment]
I'm going to guess it's been released early to patreon donors?

**Comment by peijie7788** [comment]
How do you solve this issue?

**Comment by Griffin224** [comment]
@Azanor , you marked this as solved but didn't tell us how to solve it... or is it solved in the next release?

**Comment by UnixRonin** [comment]
@Griffin224, I presume there's a hotfix coming shortly.

**Comment by Ragnarok96** [comment]
Found this issue as #841 through google, still a problem - have left my logs etc. there.

**Comment by apemanzilla** [comment]
I'm getting the same crash. Loading the same world up in singleplayer works fine though.

**Comment by enderger** [comment]
Same for my SMP lan

**Comment by enderger** [comment]
And there is a stabilizer already

**Comment by enderger** [comment]
In my base

**Comment by enderger** [comment]
AZANOR THIS IS CLEARLY NOT SOLVED!!!!!!!!!!!!

**Comment by enderger** [comment]
If anything, it’s much worse in B15
